### ISSUE TITLE
Unable to parse liquid?

### ISSUE THREAD

**Issue by seandogg** [andrewbanchich/solid-state-jekyll-theme#1]
Added a _config.yml:
`title: Some Title`

`<title>{{ site.title}}</title>` is printing as: {{ site.title }} on the site, this is after adding config and then running `bundle install` and `bundle exec jekyll serve` (also restarted the server a few times and ran `jekyll build` after adding _config.yml). 

Spooled up a fresh install in another folder, everything parses fine on a fresh minima theme.

**Comment by andrewbanchich** [comment]
hi sean, this theme is a work in progress (see "WIP" in the Read Me file). any complete themes don't have this. sorry for the confusion! i am actually working on this next so it shouldn't be too long before it's ready to go.

**Comment by seandogg** [comment]
Ah ha! Great looking theme as always my dude.
