### ISSUE TITLE
No _config.yml

### ISSUE THREAD

**Issue by devvartpoddar** [andrewbanchich/solid-state-jekyll-theme#2]
Hey @andrewbanchich,

Thanks for making a port of the solid state template by HTML5UP. I loved the themes and will be adopting one of them for my website. This one has no _config though, and I am a newbie in Jekyll. Could you help?

Best,
Dev

**Comment by seandogg** [comment]
This may help, here's a basic one that I use with this repo: https://gist.github.com/seandogg/eb5e76a9a527762873e175be04e0b08f

**Comment by devvartpoddar** [comment]
Hey Sean, thanks loads!

**Comment by andrewbanchich** [comment]
Hi @devvartpoddar, yes this is a "WIP" or "Work in Progress" repo so it isn't a functional Jekyll theme yet.
