### ISSUE TITLE
Menu does not work

### ISSUE THREAD

**Issue by alexsayal** [andrewbanchich/solid-state-jekyll-theme#4]
Hello,

I started using this theme on a new website, but found that the Menu panel does not seem to be working. After clicking, nothing happens.

Could you please check this up?

Thank you in advance,

**Comment by andrewbanchich** [comment]
Hi, this theme is actually a work in progress (which is what the WIP stands for in the README title), so that is expected. I had plans to finish adding functionality in the future, but unfortunately haven't had the time.
